Repository oslabs-beta/infernode, pull requests merged in 2022-10, with the labels that each got.

#226 fix(node.js.yml): Remove workflow-2 trigger from node.js GHA
  .github/workflows/node.js.yml
Labels: ci/cd

#204 ci (odeql-analysis.yml): Add automated code security scanning GHA
  .github/workflows/codeql-analysis.yml
Labels: testing, ci/cd

#225 fix(index.ts): modified default server port in index.ts and webpack.dev.js
  src/index.ts
  webpack.dev.js
Labels: bugfix
