Repository oslabs-beta/infernode, pull requests merged in 2022-09, with the labels that each got.

#92 Feature/perf controller
  src/controllers/dTrace.controller.ts
  src/controllers/flamegraphController.ts
  src/examples/app-test.js
  src/examples/example-task.js
  src/perlScripts/stackCollapse-Dtrace.pl
  src/routes/api.router.ts
  src/routes/dtrace.router.ts
Labels: feature

#101 Add basic Github Pages config and index.html (#99) (#100)
  .github/workflows/pages.yml
  site/index.html
Labels: docs

#103 ManagePage refactoring, remove action bugfix
  src/public/infernode/store/captureSlice.ts
  src/public/infernode/views/Manage/ManageForm.tsx
  src/public/infernode/views/Manage/ManagePage.tsx
Labels: bugfix, refactor

#104 Refactor/dtrace node backend
  src/controllers/application.controller.ts
  src/controllers/dTrace.controller.ts
  src/controllers/icicle.controller.ts
  src/examples/example-task.js
  src/routes/application.router.ts
  src/routes/captures.router.ts
  src/routes/dtrace.router.ts
Labels: feature, refactor

#106 Add activePage state, use with navbar
  src/__tests__/capturePageUnit.test.tsx
  src/__tests__/health.test.ts
  src/__tests__/jest.test.ts
  src/__tests__/managePageUnit.test.tsx
  src/public/infernode/components/layout/NavBar/NavBar.tsx
  src/public/infernode/store/configSlice.ts
  src/public/infernode/views/Capture/CapturePage.tsx
  src/public/infernode/views/Help/HelpPage.tsx
  src/public/infernode/views/History/HistoryPage.tsx
  src/public/infernode/views/Manage/ManagePage.tsx
Labels: bugfix

#105 Feature/capture page reducer
  src/public/infernode/services/appService.ts
  src/public/infernode/store/appSlice.ts
  src/public/infernode/store/store.ts
  src/public/infernode/views/Capture/AppStatusCircle.tsx
  src/public/infernode/views/Capture/CapturePage.tsx
Labels: feature

#118 Add badges and email link to readme
  .github/workflows/node.js.yml
  .github/workflows/pages.yml
  README.md
Labels: docs

#119 Feature/capture page reducer
  src/__tests__/capturePageUnit.test.tsx
  src/public/infernode/store/appSlice.ts
  src/public/infernode/views/Capture/CapturePage.tsx
  src/routes/application.router.ts
Labels: feature

#120 Add OS and sudo permissions detection
  package-lock.json
  package.json
  src/controllers/controllers.module.ts
  src/controllers/dTrace.controller.ts
  src/controllers/env.controller.ts
  src/routes/dtrace.router.ts
Labels: feature

#123 Add timeout to sudo to avoid hanging on WSL systems
  src/controllers/env.controller.ts
Labels: bugfix

#122 Add and use Node.JS logging library
  .vscode/settings.json
  package-lock.json
  package.json
  src/__tests__/middlewareUnit.test.ts
  src/controllers/db.controller.ts
  src/controllers/env.controller.ts
  src/public/infernode/views/Capture/CapturePage.tsx
  src/public/infernode/views/Help/HelpPage.tsx
  src/public/infernode/views/History/HistoryPage.tsx
  src/public/infernode/views/Manage/ManagePage.tsx
  src/routes/api.router.ts
  src/routes/captures.router.ts
  src/routes/control.router.ts
  src/server.ts
  src/utils/globalErrorHandler.ts
  src/utils/logging.ts
Labels: feature

#128 Basic linux perf capture working
  src/controllers/application.controller.ts
  src/controllers/dTrace.controller.ts
  src/controllers/env.controller.ts
  src/controllers/perf.controller.ts
  src/public/infernode/views/Capture/CapturePage.tsx
  src/routes/dtrace.router.ts
Labels: feature

#135 Add feature state, feature flag off login and captureSidebar
  src/public/infernode/components/layout/NavBar/Login.tsx
  src/public/infernode/store/configSlice.ts
  src/public/infernode/views/Capture/CaptureSidebar.tsx
Labels: feature

#140 Delete site directory
  site/index.html
Labels: bugfix

#137 Doc/website
  .eslintignore
  .eslintrc.js
  site/index.html
  site/public/About/about.css
  site/public/About/about.html
  site/public/Documentation/doc2.html
  site/public/Documentation/documentation.css
  site/public/Documentation/documentation.js
  site/public/images/Dzidupe.jpeg
  site/public/images/Github-Logo-White.png
  site/public/images/Hui.jpg
  site/public/images/Luke.jpeg
  site/public/images/Will.jpg
  site/public/images/another-blue-flame.jpg
  site/public/images/big-blue-flame.jpg
  site/public/images/chase.jpeg
  site/public/images/differential.png
  site/public/images/differential.svg
  site/public/images/flamegraph-2.svg
  site/public/images/flamegraph3.png
  site/public/images/github-logo.png
  site/public/images/icicle-2.svg
  site/public/images/icicle.png
  site/public/images/linkedin-logo.png
  site/public/images/logo-dark.png
  site/public/images/logo-light-no-name.png
  site/public/images/logo-light.png
  site/public/images/orange-flame.jpg
  site/public/images/orangeand-blue-flame.jpg
  site/public/images/twitter.png
  site/public/index.css
  site/public/index.html
Labels: docs

#142 Update pages.yml
  .github/workflows/pages.yml
Labels: ci/cd

#154 Help menu styling and content for perf/dtrace config
  src/public/infernode/App.tsx
  src/public/infernode/views/Help/HelpPages.tsx
  src/public/infernode/views/Help/HelpSidebar.tsx
Labels: docs

#163 Refactor HistorySidebar and reuse
  src/public/infernode/App.tsx
  src/public/infernode/components/layout/ListSidebar.tsx
  src/public/infernode/store/configSlice.ts
  src/public/infernode/views/Capture/CaptureFileItem.tsx
  src/public/infernode/views/Capture/CapturePage.tsx
  src/public/infernode/views/Capture/CaptureSidebar.tsx
  src/public/infernode/views/History/HistoryFileItem.tsx
  src/public/infernode/views/History/HistoryPage.tsx
  src/public/infernode/views/History/HistorySidebar.tsx
  src/public/infernode/views/Upload/UploadPage.tsx
  src/public/infernode/views/Upload/UploadSidebar.tsx
Labels: feature, refactor

#170 Capture form styling and refactoring
  src/public/infernode/components/LabeledSpinner.tsx
  src/public/infernode/components/layout/ListSidebar.tsx
  src/public/infernode/store/appSlice.ts
  src/public/infernode/views/Capture/AppStatusCircle.tsx
  src/public/infernode/views/Capture/CapturePage.tsx
  src/public/infernode/views/Help/HelpSidebar.tsx
  src/public/infernode/views/Upload/UploadForm.tsx
Labels: feature, refactor

#171 Feature/npm publish
  .github/workflows/node.js.yml
  .github/workflows/publish.yml
  package-lock.json
  package.json
Labels: ci/cd

#184 feat(scss): override bootstrap color them by refactoring scss handling #182
  .stylelintrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/assets/css/.gitkeep
  src/assets/index.html
  src/assets/styles.css
  src/public/infernode/App.scss
  src/public/infernode/App.tsx
  src/scss/styles.scss
  webpack.common.js
Labels: feature, refactor

#186 docs(LICENSE): Add MIT license file
  LICENSE
Labels: docs

#188 fix(capturemodel.ts): automatically create data storage directories o…
  database/SVGs/.gitkeep
  database/captures/.gitkeep
  database/folded/.gitkeep
  database/uploads/.gitkeep
  package.json
  src/models/.gitkeep
  src/models/captureModel.ts
  src/utils/makeDataDirs.ts
Labels: bugfix

#190 fix(perlscripts): ensure perlScripts is included in npm package build
  src/assets/perlScripts/diff-folded.pl
  src/assets/perlScripts/flamegraph.pl
  src/assets/perlScripts/stackCollapse-Dtrace.pl
  src/assets/perlScripts/stackCollapse-perf.pl
  src/controllers/dTrace.controller.ts
  src/controllers/diff.controller.ts
  src/controllers/flamegraphController.ts
  src/controllers/icicle.controller.ts
  src/controllers/perf.controller.ts
  src/examples/example-server.js
  src/examples/example-task.js
Labels: bugfix

#198 fix(react index.tsx): change react-router to MemoryRouter to fix nav
  src/public/infernode/index.tsx
Labels: bugfix

#222 Docs/readme diagram updates
  CONTRIBUTING.md
  README.md
  docs/arch-diagrams.md
Labels: docs

#223 Bugfix/capture state to redux
  src/bin/infernode.ts
  src/controllers/application.controller.ts
  src/controllers/dTrace.controller.ts
  src/controllers/diff.controller.ts
  src/controllers/env.controller.ts
  src/index.ts
  src/public/infernode/views/Capture/CapturePage.tsx
  src/server.ts
Labels: bugfix, refactor
