Repository oslabs-beta/infernode, pull requests merged in 2022-08, with the labels that each got.

#1 Document draft contribution standards
  README.md
Labels: documentation

#6 Basic typescript server with testing and CI
  .github/workflows/node.js.yml
  README.md
  jest-setup.js
  jest-teardown.js
  package-lock.json
  package.json
  src/__tests__/jest.ts
  src/assets/index.html
  src/index.ts
  tsconfig.json
  tslint.json
Labels: feature, testing

#7 Refactor and add health endpoint and associated tests
  jest-teardown.js
  package.json
  src/__tests__/health.ts
  src/assets/index.html
  src/controllers/controllers.module.ts
  src/controllers/health.controller.ts
  src/index.ts
  src/interfaces/health.interface.ts
  src/routes/health.router.ts
  src/server.ts
Labels: feature, testing, refactor

#12 Add basic React boilerplate and React-Boostrap styling
  package-lock.json
  package.json
  src/assets/index.html
  src/assets/logo-text.png
  src/assets/logo.png
  src/assets/mocks/capture-content.png
  src/assets/mocks/capture-menu.png
  src/assets/mocks/help-content.png
  src/assets/mocks/help-menu.png
  src/assets/mocks/history-content.png
  src/assets/mocks/history-menu.png
  src/assets/mocks/manage-content.png
  src/assets/mocks/manage-menu.png
  src/assets/mocks/navbar-buttons.png
  src/models/.gitkeep
  src/public/infernode/App.scss
  src/public/infernode/App.tsx
  src/public/infernode/components/layout/NavBar/NavBar.tsx
  src/public/infernode/index.tsx
  src/public/infernode/services/.gitkeep
  src/public/infernode/store/darkMode.ts
  src/public/infernode/tsconfig.json
  src/public/infernode/utils/.gitkeep
  src/public/infernode/views/Capture/CapturePage.tsx
  src/public/infernode/views/Capture/CaptureSidebar.tsx
  src/public/infernode/views/Help/HelpPage.tsx
  src/public/infernode/views/Help/HelpSidebar.tsx
  src/public/infernode/views/History/HistoryPage.tsx
  src/public/infernode/views/History/HistorySidebar.tsx
  src/public/infernode/views/Manage/ManagePage.tsx
  src/public/infernode/views/Manage/ManageSidebar.tsx
  tsconfig.json
  webpack.config.js
Labels: feature

#19 Align sidebar menus and embed example flamegraph
  .gitignore
  src/assets/mocks/history-footer.png
  src/assets/mocks/history-header.png
  src/assets/node-example-fg.svg
  src/public/infernode/App.tsx
  src/public/infernode/views/Capture/CaptureSidebar.tsx
  src/public/infernode/views/Help/HelpSidebar.tsx
  src/public/infernode/views/History/HistoryPage.tsx
  src/public/infernode/views/History/HistorySidebar.tsx
  src/public/infernode/views/Manage/ManageSidebar.tsx
Labels: bugfix

#20 Add wireframes, diagrams, tech stack to readme
  README.md
  docs/images/app-diagram.png
  docs/images/capture-page.png
  docs/images/generic-page.png
  docs/images/help-page.png
  docs/images/history-page.png
  docs/images/landing-page.png
  docs/images/layout-draft.png
  docs/images/layout-overview.png
  docs/images/manage-page.png
  docs/images/manage-workflow.png
Labels: docs

#28 Add 404, global err handler, api router
  package.json
  src/controllers/controllers.module.ts
  src/controllers/notfound.controller.ts
  src/index.ts
  src/routes/api.router.ts
  src/routes/notFound.router.ts
  src/server.ts
  src/utils/InfernodeError.class.ts
  src/utils/globalErrorHandler.ts
  tslint.json
Labels: feature

#30 Add eslint abd babel configs
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  src/public/infernode/.eslintignore
  src/public/infernode/.eslintrc.js
  src/public/infernode/babel.config.json
  src/public/infernode/tsconfig.json
  webpack.config.js
Labels: testing

#31 Svg middleware
  .vscode/settings.json
  package-lock.json
  src/controllers/flamegraphController.ts
  src/index.ts
  src/perlScripts/flamegraph.pl
  src/perlScripts/stackCollapse-perf.pl
  src/routes/api.router.ts
  src/server.ts
Labels: feature

#32 Feature/filecontroller
  package-lock.json
  package.json
  src/controllers/controllers.module.ts
  src/controllers/file.controller.ts
  src/public/infernode/views/Manage/ManagePage.tsx
  src/routes/api.router.ts
Labels: feature

#35 Partial eslint config + fixes, webpack config refactor
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  src/assets/index.html
  src/controllers/controllers.module.ts
  src/controllers/file.controller.ts
  src/controllers/flamegraphController.ts
  src/controllers/health.controller.ts
  src/controllers/notfound.controller.ts
  src/index.ts
  src/interfaces/health.interface.ts
  src/models/captureModel.ts
  src/public/infernode/.eslintrc.js
  src/public/infernode/App.scss
  src/public/infernode/App.tsx
  src/public/infernode/components/layout/NavBar/NavBar.tsx
  src/public/infernode/index.tsx
  src/public/infernode/store/.gitkeep
  src/public/infernode/store/darkMode.ts
  src/public/infernode/tsconfig.json
  src/public/infernode/views/Capture/CapturePage.tsx
  src/public/infernode/views/Capture/CaptureSidebar.tsx
  src/public/infernode/views/Help/HelpPage.tsx
  src/public/infernode/views/Help/HelpPages.tsx
  src/public/infernode/views/Help/HelpSidebar.tsx
  src/public/infernode/views/History/HistoryPage.tsx
  src/public/infernode/views/History/HistorySidebar.tsx
  src/public/infernode/views/Manage/ManagePage.tsx
  src/public/infernode/views/Manage/ManageSidebar.tsx
  src/routes/api.router.ts
  src/routes/health.router.ts
  src/routes/notFound.router.ts
  src/server.ts
  src/utils/InfernodeError.class.ts
  src/utils/globalErrorHandler.ts
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: testing, refactor

#47 Bugfix/flamegraph controller tying issue
  src/controllers/flamegraphController.ts
Labels: bugfix

#50 Connect file.controller and flamegraphController
  src/controllers/file.controller.ts
  src/routes/api.router.ts
Labels: feature

#51 Add state management to frontend
  .vscode/settings.json
  package-lock.json
  package.json
  src/public/infernode/components/layout/NavBar/Login.tsx
  src/public/infernode/components/layout/NavBar/NavBar.tsx
  src/public/infernode/index.tsx
  src/public/infernode/store/captureSlice.ts
  src/public/infernode/store/configSlice.ts
  src/public/infernode/store/hooks.ts
  src/public/infernode/store/store.ts
  src/public/infernode/store/userSlice.ts
Labels: feature, refactor

#46 Enforce linting on PR, update readme with dev details
  .eslintrc.js
  .gitignore
  .vscode/settings.json
  README.md
  database/folded/.gitkeep
  database/uploads/.gitkeep
  package.json
  src/controllers/file.controller.ts
  src/controllers/flamegraphController.ts
  src/models/captureModel.ts
  src/routes/api.router.ts
Labels: docs, testing

#53 Feature/db controller
  src/controllers/db.controller.ts
  src/interfaces/dbcontroller.interface.ts
  src/models/captureModel.ts
  src/routes/api.router.ts
  src/server.ts
Labels: feature

#48 Feature/histroy page display svg component
  .eslintrc.js
  package-lock.json
  package.json
  src/assets/fg.svg
  src/assets/styles.css
  src/controllers/file.controller.ts
  src/public/infernode/.eslintrc.js
  src/public/infernode/store/captureSlice.ts
  src/public/infernode/views/History/HistoryFileItem.tsx
  src/public/infernode/views/History/HistoryPage.tsx
  src/public/infernode/views/History/HistorySidebar.tsx
  src/public/infernode/views/History/custom.d.ts
  src/routes/api.router.ts
  tsconfig.json
  webpack.common.js
Labels: feature

#61 Feature/histroy page sidebar
  src/public/infernode/store/captureSlice.ts
  src/public/infernode/views/History/HistoryFileItem.tsx
  src/public/infernode/views/History/HistoryPage.tsx
  src/public/infernode/views/History/HistorySidebar.tsx
  src/public/infernode/views/History/custom.d.ts
Labels: feature

#63 Add fetchAllCaptures reducer and wiring
  .vscode/settings.json
  package-lock.json
  package.json
  src/controllers/file.controller.ts
  src/public/infernode/App.tsx
  src/public/infernode/services/Api.ts
  src/public/infernode/services/captureService.ts
  src/public/infernode/store/captureSlice.ts
  src/public/infernode/store/interfaces.ts
  src/routes/api.router.ts
Labels: feature

#69 Add deleteOne and updateOne captures reducers
  package-lock.json
  package.json
  src/public/infernode/App.tsx
  src/public/infernode/services/captureService.ts
  src/public/infernode/store/captureSlice.ts
  src/public/infernode/views/History/HistorySidebar.tsx
Labels: feature

#64 Feature/histroy page sidebar
  .eslintrc.js
  src/__tests__/managePageUnit.test.tsx
  src/__tests__/routeIntegration.test.ts
  src/public/infernode/store/captureSlice.ts
  src/public/infernode/views/Manage/ManagePage.tsx
  src/routes/api.router.ts
Labels: bugfix, feature

#72 Feature/controller merge
  .gitignore
  src/controllers/db.controller.ts
  src/interfaces/dbcontroller.interface.ts
  src/models/captureModel.ts
  src/routes/api.router.ts
Labels: bugfix, feature, refactor

#77 Release/1.0.0
  README.md
  package.json
  src/public/infernode/App.tsx
Labels: docs

#87 Add CDDL as referenced by flamegraph tools
  docs/cddl1.txt
Labels: docs

#88 Add 2 simple JS apps for flamegraph capture testing
  .eslintrc.js
  src/__tests__/middlewareUnit.test.ts
  src/examples/example-server.js
  src/examples/example-task.js
  tsconfig.json
Labels: testing

#89 Refactor router and add control router
  src/routes/api.router.ts
  src/routes/captures.router.ts
  src/routes/control.router.ts
Labels: refactor

#91 Manage page form updates and misc fixes
  package-lock.json
  package.json
  src/__tests__/managePageUnit.test.tsx
  src/controllers/file.controller.ts
  src/public/infernode/components/layout/ProgressCard.tsx
  src/public/infernode/store/interfaces.ts
  src/public/infernode/store/store.ts
  src/public/infernode/store/uploadSlice.ts
  src/public/infernode/views/History/HistoryFileItem.tsx
  src/public/infernode/views/History/HistorySidebar.tsx
  src/public/infernode/views/Manage/ManagePage.tsx
  src/routes/captures.router.ts
Labels: bugfix, feature, refactor
